<?php

namespace Database\Seeders;

use App\Models\Permohonan;
use Illuminate\Database\Seeder;

class PermohonanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $samples = [
            [
                'no_registrasi' => 'EXT0420269900',
                'pemohon' => 'Lim Kok Wei',
                'jenis_permohonan' => 'Pelayanan Perpanjangan Hak Atas Tanah',
                'surat_permohonan' => 'SP-20260805-001',
                'nomor_pl' => '226.97.96040000.B1.000',
                'no_spj_ppt' => '7000/A2.3/L/6/2026',
                'no_rekom' => 'B-4600/KA-A2-A2.3/6/2026',
                'no_skep_kpt' => '6300/A2.3/L/6/2026',
                'pembeli' => '-',
                'tanggal_surat' => '2026-08-05',
                'status_proses' => 'Diproses',
                'status_verifikasi' => 'Terverifikasi',
                'waktu_menunggu' => null,
                'ditugaskan' => 'Rahmat Ikraldo Busyra',
                'check_sppt' => true,
                'check_sp' => true,
                'check_skpt' => true,
                'check_skpl_sppl_lama' => true,
                'check_pl' => true,
                'check_pl_lama' => true,
                'keterangan_petugas' => 'Dokumen lengkap, diserahkan langsung oleh pemohon.',
                'file_tanda_terima' => 'permohonan_files/tanda-terima-EXT0420269900.jpg',
                'uploaded_by_name' => 'Rahmat Ikraldo Busyra',
            ],
            [
                'no_registrasi' => 'EXT0420269899',
                'pemohon' => 'Siti Rohaya',
                'jenis_permohonan' => 'Pelayanan Perpanjangan Hak Atas Tanah',
                'surat_permohonan' => 'SP-20260805-002',
                'nomor_pl' => '226.97.96040000.B1.001',
                'no_spj_ppt' => '7000/A2.3/L/6/2026',
                'no_rekom' => 'B-4600/KA-A2-A2.3/6/2026',
                'no_skep_kpt' => '6300/A2.3/L/6/2026',
                'pembeli' => '-',
                'tanggal_surat' => '2026-08-05',
                'status_proses' => 'Selesai',
                'status_verifikasi' => 'Terverifikasi',
                'waktu_menunggu' => null,
                'ditugaskan' => 'Jaka Prasetya',
                'check_sppt' => true,
                'check_sp' => true,
                'check_skpt' => true,
                'check_skpl_sppl_lama' => true,
                'check_pl' => true,
                'check_pl_lama' => false,
                'keterangan_petugas' => 'Dokumen 5/6 lengkap.',
                'file_tanda_terima' => null,
                'uploaded_by_name' => 'Jaka Prasetya',
            ],
            [
                'no_registrasi' => 'EXT0420269898',
                'pemohon' => 'Fitri Handayani',
                'jenis_permohonan' => 'Pelayanan Perpanjangan Hak Atas Tanah',
                'surat_permohonan' => 'SP-20260805-003',
                'nomor_pl' => '226.97.96040000.B1.002',
                'no_spj_ppt' => '7000/A2.3/L/6/2026',
                'no_rekom' => 'B-4600/KA-A2-A2.3/6/2026',
                'no_skep_kpt' => '6300/A2.3/L/6/2026',
                'pembeli' => '-',
                'tanggal_surat' => '2026-08-05',
                'status_proses' => 'Selesai',
                'status_verifikasi' => 'Menunggu',
                'waktu_menunggu' => '0h',
                'ditugaskan' => 'Wiendi Andriyani',
                'check_sppt' => false,
                'check_sp' => false,
                'check_skpt' => false,
                'check_skpl_sppl_lama' => false,
                'check_pl' => false,
                'check_pl_lama' => false,
                'keterangan_petugas' => 'Menunggu pemeriksaan fisik berkas.',
                'file_tanda_terima' => null,
                'uploaded_by_name' => 'Wiendi Andriyani',
            ],
            [
                'no_registrasi' => 'EXT0420269897',
                'pemohon' => 'Agus Salim Hasibuan',
                'jenis_permohonan' => 'Pelayanan Perpanjangan Hak Atas Tanah',
                'surat_permohonan' => 'SP-20260804-010',
                'nomor_pl' => '226.97.96040000.B1.003',
                'no_spj_ppt' => '7000/A2.3/L/6/2026',
                'no_rekom' => 'B-4600/KA-A2-A2.3/6/2026',
                'no_skep_kpt' => '6300/A2.3/L/6/2026',
                'pembeli' => '-',
                'tanggal_surat' => '2026-08-04',
                'status_proses' => 'Selesai',
                'status_verifikasi' => 'Menunggu',
                'waktu_menunggu' => '1h',
                'ditugaskan' => 'Rahmat Ikraldo Busyra',
                'check_sppt' => false,
                'check_sp' => false,
                'check_skpt' => false,
                'check_skpl_sppl_lama' => false,
                'check_pl' => false,
                'check_pl_lama' => false,
                'keterangan_petugas' => 'Menunggu verifikasi lanjutan.',
                'file_tanda_terima' => null,
                'uploaded_by_name' => 'Rahmat Ikraldo Busyra',
            ],
            [
                'no_registrasi' => 'EXT0420269896',
                'pemohon' => 'Zainal Abidin',
                'jenis_permohonan' => 'Pelayanan Peralihan Hak Atas Tanah',
                'surat_permohonan' => 'SP-20260804-011',
                'nomor_pl' => '226.97.96040000.B1.004',
                'no_spj_ppt' => '7000/A2.3/L/6/2026',
                'no_rekom' => 'B-4600/KA-A2-A2.3/6/2026',
                'no_skep_kpt' => '6300/A2.3/L/6/2026',
                'pembeli' => 'PT Sukses Makmur',
                'tanggal_surat' => '2026-08-04',
                'status_proses' => 'Selesai',
                'status_verifikasi' => 'Terverifikasi',
                'waktu_menunggu' => null,
                'ditugaskan' => 'Jaka Prasetya',
                'check_sppt' => true,
                'check_sp' => true,
                'check_skpt' => true,
                'check_skpl_sppl_lama' => true,
                'check_pl' => false,
                'check_pl_lama' => false,
                'keterangan_petugas' => 'Berkas terverifikasi 4/6.',
                'file_tanda_terima' => null,
                'uploaded_by_name' => 'Jaka Prasetya',
            ],
            [
                'no_registrasi' => 'EXT0420269895',
                'pemohon' => 'Robert Tampubolon',
                'jenis_permohonan' => 'Pelayanan Perpanjangan Hak Atas Tanah',
                'surat_permohonan' => 'SP-20260804-012',
                'nomor_pl' => '226.97.96040000.B1.005',
                'no_spj_ppt' => '7000/A2.3/L/6/2026',
                'no_rekom' => 'B-4600/KA-A2-A2.3/6/2026',
                'no_skep_kpt' => '6300/A2.3/L/6/2026',
                'pembeli' => '-',
                'tanggal_surat' => '2026-08-04',
                'status_proses' => 'Diproses',
                'status_verifikasi' => 'Terverifikasi',
                'waktu_menunggu' => null,
                'ditugaskan' => 'Wiendi Andriyani',
                'check_sppt' => true,
                'check_sp' => true,
                'check_skpt' => true,
                'check_skpl_sppl_lama' => true,
                'check_pl' => false,
                'check_pl_lama' => false,
                'keterangan_petugas' => 'Dokumen diproses verifikasi.',
                'file_tanda_terima' => null,
                'uploaded_by_name' => 'Wiendi Andriyani',
            ],
            [
                'no_registrasi' => 'EXT0420269894',
                'pemohon' => 'Muhammad Ridwan',
                'jenis_permohonan' => 'Pelayanan Perpanjangan Hak Atas Tanah',
                'surat_permohonan' => 'SP-20260803-020',
                'nomor_pl' => '226.97.96040000.B1.006',
                'no_spj_ppt' => '7000/A2.3/L/6/2026',
                'no_rekom' => 'B-4600/KA-A2-A2.3/6/2026',
                'no_skep_kpt' => '6300/A2.3/L/6/2026',
                'pembeli' => '-',
                'tanggal_surat' => '2026-08-03',
                'status_proses' => 'Selesai',
                'status_verifikasi' => 'Menunggu',
                'waktu_menunggu' => '2h',
                'ditugaskan' => 'Rahmat Ikraldo Busyra',
                'check_sppt' => false,
                'check_sp' => false,
                'check_skpt' => false,
                'check_skpl_sppl_lama' => false,
                'check_pl' => false,
                'check_pl_lama' => false,
                'keterangan_petugas' => 'Menunggu konfirmasi pemohon.',
                'file_tanda_terima' => null,
                'uploaded_by_name' => 'Rahmat Ikraldo Busyra',
            ],
            [
                'no_registrasi' => 'EXT0420269893',
                'pemohon' => 'Rina Marlina',
                'jenis_permohonan' => 'Pelayanan Peralihan Hak Atas Tanah',
                'surat_permohonan' => 'SP-20260803-021',
                'nomor_pl' => '226.97.96040000.B1.007',
                'no_spj_ppt' => '7000/A2.3/L/6/2026',
                'no_rekom' => 'B-4600/KA-A2-A2.3/6/2026',
                'no_skep_kpt' => '6300/A2.3/L/6/2026',
                'pembeli' => 'Hengky Wijaya',
                'tanggal_surat' => '2026-08-03',
                'status_proses' => 'Selesai',
                'status_verifikasi' => 'Menunggu',
                'waktu_menunggu' => '2h',
                'ditugaskan' => 'Jaka Prasetya',
                'check_sppt' => false,
                'check_sp' => false,
                'check_skpt' => false,
                'check_skpl_sppl_lama' => false,
                'check_pl' => false,
                'check_pl_lama' => false,
                'keterangan_petugas' => 'Menunggu kelengkapan SKPT.',
                'file_tanda_terima' => null,
                'uploaded_by_name' => 'Jaka Prasetya',
            ],
        ];

        // Fill remaining up to 30 sample rows
        $names = ['Budi Santoso', 'Dewi Lestari', 'Eko Prasetyo', 'Hendra Gunawan', 'Indah Permata', 'Joko Widodo', 'Kartika Putri', 'Lia Ananda', 'Made Suardana', 'Nurul Hidayah', 'Oktavianus', 'Putu Gede', 'Qori Sandioriva', 'Rudi Hartono', 'Sri Wahyuni', 'Taufik Hidayat', 'Umar Faruq', 'Vina Panduwinata', 'Wawan Setiawan', 'Yusuf Mansur', 'Zahra Amalia', 'Andi Pratama'];
        $officers = ['Rahmat Ikraldo Busyra', 'Jaka Prasetya', 'Wiendi Andriyani'];
        $types = ['Pelayanan Perpanjangan Hak Atas Tanah', 'Pelayanan Peralihan Hak Atas Tanah', 'Pelayanan Pelepasan Hak Atas Tanah'];

        foreach ($samples as $item) {
            Permohonan::updateOrCreate(['no_registrasi' => $item['no_registrasi']], $item);
        }

        for ($i = 0; $i < 22; $i++) {
            $regNum = 'EXT04202698' . sprintf('%02d', 92 - $i);
            Permohonan::updateOrCreate(
                ['no_registrasi' => $regNum],
                [
                    'pemohon' => $names[$i % count($names)],
                    'jenis_permohonan' => $types[$i % count($types)],
                    'surat_permohonan' => 'SP-202608' . sprintf('%02d', rand(1, 4)) . '-' . sprintf('%03d', rand(1, 99)),
                    'nomor_pl' => '226.97.96040000.B1.' . sprintf('%03d', $i + 10),
                    'no_spj_ppt' => '7000/A2.3/L/6/2026',
                    'no_rekom' => 'B-4600/KA-A2-A2.3/6/2026',
                    'no_skep_kpt' => '6300/A2.3/L/6/2026',
                    'pembeli' => '-',
                    'tanggal_surat' => '2026-08-0' . rand(1, 5),
                    'status_proses' => $i % 3 == 0 ? 'Diproses' : 'Selesai',
                    'status_verifikasi' => $i % 2 == 0 ? 'Terverifikasi' : 'Menunggu',
                    'waktu_menunggu' => $i % 2 == 0 ? null : rand(1, 5) . 'h',
                    'ditugaskan' => $officers[$i % count($officers)],
                    'check_sppt' => rand(0, 1) == 1,
                    'check_sp' => rand(0, 1) == 1,
                    'check_skpt' => rand(0, 1) == 1,
                    'check_skpl_sppl_lama' => rand(0, 1) == 1,
                    'check_pl' => rand(0, 1) == 1,
                    'check_pl_lama' => rand(0, 1) == 1,
                    'keterangan_petugas' => 'Dokumen hasil impor berkas pertanahan BP Batam.',
                    'file_tanda_terima' => null,
                    'uploaded_by_name' => $officers[$i % count($officers)],
                ]
            );
        }
    }
}
